%include "colon.inc"

section .data

colon "Corgi", corgi
db "Small foxey brave-heart shepherd", 0

colon "Pug", pug
db "Grey, fat & slobbery", 0

colon "Beagle", beagle
db "Spotty energizer", 0

colon "Chihuahua", chihuahua
db "Small, useless and always barking", 0

colon "German Shepherd", german_shepherd
db "Big not-foxey brave-heart, but still shepherd", 0

colon "Doberman", doberman
db "Graceful, brave and very cool", 0
